version: '3'

services:
  nuxt:
    build:
      context: .
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - ./:/opt/app:cached
    ports:
      - '3333:3333'
      - '5555:5555'
      - '24678:24678'
    command: sh -c "rm -rf '/tmp/nitro/' && yarn install && yarn dev"

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    healthcheck:
      test: [ 'CMD', '/usr/local/bin/healthcheck.sh', '--connect' ]
      interval: 5s
      timeout: 2s
      retries: 20
